### ISSUE TITLE
IntelliJ version compatibility?

### ISSUE THREAD

**Issue by javaduke** [machaval/mule-esb-plugin#1]
Mariano, which version of IntelliJ this plugin is compatible with? I'm getting compatibility error message when trying to install it on IntelliJ 15 CE.

**Comment by machaval** [comment]
What compatibilty errors? I've tested with Intellij 14 and 15 in mac and linux and it worked. Can you attach the stack trace

**Comment by cysnake4713** [comment]
Nice Work! I'll try it soon!

**Comment by machaval** [comment]
@cysnake4713 @javaduke  Just one comment the plugin is still in early stage. It can be done but there still serveral issues, specially I'm finding issues with the breakpoints. Please if you can report them

**Comment by cysnake4713** [comment]
Already using it now, so far everything is ok, haven't use debug yet, run with mule standalone version seems work perfect.

**Comment by javaduke** [comment]
I'm still unable to install the plugin. I have the latest IntelliJ IDEA 15.0.3. When I try to install the plugin, I get the error message: "Plugin 'Mule Plugin for IntelliJ is incompatible with this installation". I don't see any other messages in the log or elsewhere.
<img width="413" alt="screen shot 2016-02-28 at 8 10 31 am" src="https://cloud.githubusercontent.com/assets/561559/13380271/96ecf956-ddf3-11e5-9cee-259ba79bec3f.png">

**Comment by machaval** [comment]
@javaduke Hi are you using the CE version or the EE version of intellij. I haven't tried with the EE version yet.

**Comment by javaduke** [comment]
Yes, CE. I got it partially working with CE 16 Early Access Preview. There are quite a few issues, but I'm not sure if this is normal, or bugs, or something is not right on my environment (I really hope it is my environment and not a bug). We'll chat tomorrow hopefully.
