### ISSUE TITLE
When new Mule XML file is created, it is not added to the mule-deploy.properties

### ISSUE THREAD

**Issue by javaduke** [machaval/mule-esb-plugin#6]
I have to edit the file manually so that it is recognized by Mule.

**Comment by javaduke** [comment]
Also, I saw there's a new Mule Maven project type :+1: I tried creating a new project with it, but mule-deploy.properties are not created automatically. I guess this is the same issue.

**Comment by machaval** [comment]
The new project is still a work in progress. I'm still playing with it.

**Comment by javaduke** [comment]
I guess this can be closed?
